### PR TITLE
doc: initial the doc structure

### PR DESCRIPTION
**Pull request by jwcesign**
doc: initial the doc structure

### CODE REVIEW

**Comment by jwcesign** [comment]
The code block is a little bit ugly, do you have any idea to make it more beautiful? @SukkaW 

image

**Comment by SukkaW** [comment]
> The code block is a little bit ugly, do you have any idea to make it more beautiful? @SukkaW
> 
> image

Try using `bash` or `shell` in the backtick code block which might help the docusaurus identify the proper syntax highlight to use.

I can take a look at the theme to see what I can do!

**Comment by jwcesign** [comment]
cc @helen-frank @SukkaW for checking

**Review by helen-frank — APPROVED** [review]

**Pull request merged**
